# Generated by Django 2.0.7 on 2018-09-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calorias', models.DecimalField(decimal_places=10, max_digits=20)),
                ('proteinas', models.DecimalField(decimal_places=10, max_digits=20)),
                ('calcio', models.DecimalField(decimal_places=10, max_digits=20)),
                ('hierro', models.DecimalField(decimal_places=10, max_digits=20)),
                ('vitamina_a', models.DecimalField(decimal_places=10, max_digits=20)),
                ('vitamina_b1', models.DecimalField(decimal_places=10, max_digits=20)),
                ('vitamina_b2', models.DecimalField(decimal_places=10, max_digits=20)),
                ('vitamina_b3', models.DecimalField(decimal_places=10, max_digits=20)),
                ('vitamina_c', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentacion.Alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_desayuno', models.BooleanField(default=True)),
                ('es_almuerzo', models.BooleanField(default=True)),
                ('es_comida', models.BooleanField(default=True)),
                ('es_merienda', models.BooleanField(default=True)),
                ('es_cena', models.BooleanField(default=True)),
                ('alimentos', models.ManyToManyField(to='alimentacion.Cantidad')),
            ],
        ),
    ]
