# Generated by Django 2.0.7 on 2018-09-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0002_auto_20180903_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='unidad',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cantidad',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
